### PR TITLE
#161066141 Design login page UI 

### PR DESCRIPTION
**Pull request by bryanmwaniqi**
**What does this PR do?**

Provides for the login page and lists  App features

**Description of Task to be completed?**

login page user interface

login page styling with css

**How should this be manually tested?**
clone the https://github.com/bryanmwaniqi/store-manager.git repo into a local repo and open the login.html file in a browser of your choice

**Screenshot**
login_page

**What are the relevant pivotal tracker stories?**

#161066141

### CODE REVIEW

**Comment by kwanj-k** [comment]
change the base branch

**Comment by JoshuaKodhe** [comment]
Greate color blending there.

**Comment by andrewhingah** [comment]
Looks good. But I believe you should be comparing your PRs with gh-pages, or whichever branch you'll finally merge to

**Comment by bryanmwaniqi** [comment]
yeah, the branch thing sure

**Pull request merged**
